# Generated by Django 3.1.6 on 2021-02-23 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='item',
        ),
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(related_name='menus', to='customers.Item'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='customers.customer'),
        ),
    ]
